_BASE_: "./hr_trans_msd_base_seg.yaml"
MODEL:
  OUT_CHANNEL: 3
  WEIGHTS: "/home/ljm/Fdisk_A/train_outputs/train_output_medical/HR_TRANS_Results/MSD/Liver/msd_liver_hr_trans_monai_stages_4_wo_x0_epochs_300/model_best.pth"
  FEATURE_SIZE: 96
  HR_TRANS:
    USING_DS_STEM: False
    STAGE_NUM: 2
    FUSION_TYPE: "res_conv"     # fc, res_conv
    DROPOUT_RATE: 0.2

INPUT:
  SPACING:
    X: 1.0
    Y: 1.0
    Z: 1.0
  SCALE_INTENSITY:
    ORIGINAL_MIN: -17.0
    ORIGINAL_MAX: 201.0
  RAND_CROP:
    ROI:
      X: 96
      Y: 96
      Z: 96

DATASETS:
  DATA_DIR: ""
  MSD_TYPE: "Liver"    # Liver, Pancreas, Spleen
  MSD:
    # Pancreas: train: 187, val: 187-234, test 234:
    # Liver: train 87, val: 87-109, test: 109
    # Spleen: 29, 35,
    TRAIN_NUM: 87
    VAL_NUM: 109
    TEST_NUM: 109

OUTPUT_DIR: "/home/ljm/Fdisk_A/train_outputs/train_output_medical/HR_TRANS_Results/MSD/Liver/msd_liver_hr_trans_monai_stages_4_wo_x0_epochs_300/"
MODE: "test"    # [train, test]