_BASE_: "./dataset_path.yaml"
MODEL:
  NAME: "swin_unetr"
  NORM: "instance"
  IN_CHANNEL: 1
  OUT_CHANNEL: 14
  DROPOUT_RATE: 0.0
  ATTN_DROPOUT_RATE: 0.0
  WEIGHTS: ""
#  WEIGHTS: "/home/ljm/Fdisk_A/train_outputs/train_output_medical/abdomen_swin_unetr_2022_6_6/model_best.pth"
  FEATURE_SIZE: 48
  USE_CHECKPOINT: False
  SSL_PRETRAINED: False
  SWIN:
    DEPTH: [2, 2, 2, 1]
    NUM_HEADS: [3, 6, 12, 24]
    SPATIAL_DIMS: 3
    WINDOW_SIZE: 7
    DROP_PATH_RATE: 0.0
    MLP_RATE: 4.0
    QKV_BIAS: True
    PATCH_SIZE: 2

INPUT:
  ORIENTATION: "RSA"
  SPACING:
    X: 1.5
    Y: 1.5
    Z: 2.0
    IMG_MODE: "bilinear"
    LAB_MODEL: "nearest"
  SCALE_INTENSITY:
    ORIGINAL_MIN: -175.0
    ORIGINAL_MAX: 250.0
    TARGET_MIN: 0.0
    TARGET_MAX: 1.0
  RAND_CROP:
    SAMPLES: 2
    POS: 1
    NEG: 1
    ROI:
      X: 96
      Y: 96
      Z: 96
  RAND:
    FLIP_AXIS_PROB: 0.2
    ROTATE90_PROB: 0.2
    SCALE_INTENSITY_PROB: 0.1
    SHIFT_INTENSITY_PROB: 0.1
  FORMAT: "NII"

DATASETS:
  JSON: "dataset_0.json"
  DATA_DIR: ""
  DATASET_TYPE: "ABDOMEN"
  NAME: "ABDOMEN"
  TYPE: "CACHE"
  CACHE:
    NUM: 24
    RATE: 1.0
  TEST_TYPE: "validation"

DATALOADER:
  TRAIN_WORKERS: 8
  TEST_WORKERS: 2

SOLVER:
  EPOCHS: 10000
  BATCH_SIZE: 1
  SW_BATCH_SIZE_TRAIN: 4
  SW_BATCH_SIZE_TEST: 4
  LR: 1e-4
  WEIGHT_DEACY: 1e-5
  MOMENTUM: 0.99
  OPTIM_ALGO: "adamw"
  EVAL_PERIOD: 100
  DROPOUT_RATE: 0.0
  INFER_OVERLAP: 0.5
  LR_SCHEDULE: "warmup_cosine"
  WARMUP_EPOCHS: 50
  SMOOTH_DR: 1e-6
  SMOOTH_NR: 0.0
  RESUME_CKPT: False
  RESUME_JIT: False
  AMP: True
  LOSS: "CEDICE"

OUTPUT_DIR: "/home/ljm/Fdisk_A/train_outputs/train_output_medical/swin_unter_test/"
SEED: 121
MODE: "train"    # [train, test]