_BASE_: "./dataset_path.yaml"
MODEL:
  NAME: "vt_unet"
  NORM: "instance"
  IN_CHANNEL: 1
  DROPOUT_RATE: 0.0
  ATTN_DROPOUT_RATE: 0.0
  USE_CHECKPOINT: False
  SSL_PRETRAINED: False
  SWIN:
    DEPTH: [2, 2, 2, 1]
    NUM_HEADS: [3, 6, 12, 24]
    SPATIAL_DIMS: 3
    WINDOW_SIZE: 7
    DROP_PATH_RATE: 0.2
    MLP_RATE: 4.0
    QKV_BIAS: True
    PATCH_SIZE: 4

  VT_UNET:
    DEPTHS: [ 2, 2, 2, 1]
    FINAL_UPSAMPLE: "expand_first"
    FROZEN_STAGES: -1

INPUT:
  ORIENTATION: "RSA"
  SPACING:
    IMG_MODE: "bilinear"
    LAB_MODEL: "nearest"
  SCALE_INTENSITY:
    TARGET_MIN: 0.0
    TARGET_MAX: 1.0
  RAND_CROP:
    SAMPLES: 1
    POS: 1
    NEG: 1
  RAND:
    FLIP_AXIS_PROB: 0.2
    ROTATE90_PROB: 0.2
    SCALE_INTENSITY_PROB: 0.1
    SHIFT_INTENSITY_PROB: 0.1
  FORMAT: "NII"

DATASETS:
  NAME: "MSD"
  TYPE: "CACHE"
  DATASET_TYPE: "MSD"
  CACHE:
#    NUM: 24
    RATE: 0.5
  TEST_TYPE: "validation"

DATALOADER:
  TRAIN_WORKERS: 2
  TEST_WORKERS: 2

SOLVER:
  EPOCHS: 300
  BATCH_SIZE: 1
  SW_BATCH_SIZE_TRAIN: 4
  SW_BATCH_SIZE_TEST: 4
  LR: 1e-4
  WEIGHT_DEACY: 1e-5
  MOMENTUM: 0.99
  OPTIM_ALGO: "adamw"
  EVAL_PERIOD: 10
  DROPOUT_RATE: 0.0
  INFER_OVERLAP: 0.5
  LR_SCHEDULE: "warmup_cosine"
  WARMUP_EPOCHS: 50
  SMOOTH_DR: 1e-6
  SMOOTH_NR: 0.0
  RESUME_CKPT: False
  RESUME_JIT: False
  AMP: True
  LOSS: "CEDICE"

SEED: 666